/*

 LONGWATER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\nimbfire\Documents\gbdk\the_game\assets\sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LongWaterWidth 20
#define LongWaterHeight 18
#define LongWaterBank 0

extern unsigned char LongWater[];

/* End of LONGWATER.H */
