/*

 MAP4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : parque_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map4Width 20
#define Map4Height 18
#define Map4Bank 0

extern unsigned char Map4[];

/* End of MAP4.H */
