/*

 MAP8.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : parque_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map8Width 20
#define Map8Height 18
#define Map8Bank 0

extern unsigned char Map8[];

/* End of MAP8.H */
