/*

 MAP_1_TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\nimbfire\Documents\gbdk\the_game\assets\sprites_map_test.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map1testWidth 20
#define Map1testHeight 18
#define Map1testBank 0

extern unsigned char Map1test[];

/* End of MAP_1_TEST.H */
