/*

 MAPHUB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : parque_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapHubWidth 20
#define MapHubHeight 18
#define MapHubBank 0

extern unsigned char MapHub[];

/* End of MAPHUB.H */
