/*

 MAPSAVEDOG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : parque_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapSaveDogWidth 20
#define MapSaveDogHeight 18
#define MapSaveDogBank 0

extern unsigned char MapSaveDog[];

/* End of MAPSAVEDOG.H */
