/*

 MAPTEACHJUMPOVERICE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 9
   Tile set      : parque_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapTeachJumpOverIceWidth 10
#define mapTeachJumpOverIceHeight 9
#define mapTeachJumpOverIceBank 0

extern unsigned char mapTeachJumpOverIce[];

/* End of MAPTEACHJUMPOVERICE.H */
