/*

 MAPBUNNYWATERICEABISMCRAZY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapBunnyWaterIceAbismCrazyWidth 20
#define MapBunnyWaterIceAbismCrazyHeight 18
#define MapBunnyWaterIceAbismCrazyBank 0

extern unsigned char MapBunnyWaterIceAbismCrazy[];

/* End of MAPBUNNYWATERICEABISMCRAZY.H */
