/*

 MAPBUNNYWATEREASY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapBunnyWaterEasyWidth 20
#define MapBunnyWaterEasyHeight 18
#define MapBunnyWaterEasyBank 0

extern unsigned char MapBunnyWaterEasy[];

/* End of MAPBUNNYWATEREASY.H */
