/*

 MAPBUNNYWATERICEABISMCRAZY2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapBunnyWaterIceAbismCrazy2Width 20
#define MapBunnyWaterIceAbismCrazy2Height 18
#define MapBunnyWaterIceAbismCrazy2Bank 0

extern unsigned char MapBunnyWaterIceAbismCrazy2[];

/* End of MAPBUNNYWATERICEABISMCRAZY2.H */
