/*

 MAPFORESTKEYMEDIUM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapForestKeyMediumWidth 20
#define MapForestKeyMediumHeight 18
#define MapForestKeyMediumBank 0

extern unsigned char MapForestKeyMedium[];

/* End of MAPFORESTKEYMEDIUM.H */
