/*

 SPRITESPARK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sprites_parkBank 0

/* Super Gameboy palette 0 */
#define sprites_parkSGBPal0c0 6076
#define sprites_parkSGBPal0c1 8935
#define sprites_parkSGBPal0c2 6596
#define sprites_parkSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define sprites_parkSGBPal1c0 6076
#define sprites_parkSGBPal1c1 8935
#define sprites_parkSGBPal1c2 6596
#define sprites_parkSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sprites_parkSGBPal2c0 6076
#define sprites_parkSGBPal2c1 8935
#define sprites_parkSGBPal2c2 6596
#define sprites_parkSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sprites_parkSGBPal3c0 6076
#define sprites_parkSGBPal3c1 8935
#define sprites_parkSGBPal3c2 6596
#define sprites_parkSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sprites_parkCGBPal0c0 6076
#define sprites_parkCGBPal0c1 8935
#define sprites_parkCGBPal0c2 6596
#define sprites_parkCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define sprites_parkCGBPal1c0 6076
#define sprites_parkCGBPal1c1 8935
#define sprites_parkCGBPal1c2 6596
#define sprites_parkCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define sprites_parkCGBPal2c0 6076
#define sprites_parkCGBPal2c1 8935
#define sprites_parkCGBPal2c2 6596
#define sprites_parkCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define sprites_parkCGBPal3c0 6076
#define sprites_parkCGBPal3c1 8935
#define sprites_parkCGBPal3c2 6596
#define sprites_parkCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define sprites_parkCGBPal4c0 6076
#define sprites_parkCGBPal4c1 8935
#define sprites_parkCGBPal4c2 6596
#define sprites_parkCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define sprites_parkCGBPal5c0 6076
#define sprites_parkCGBPal5c1 8935
#define sprites_parkCGBPal5c2 6596
#define sprites_parkCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sprites_parkCGBPal6c0 6076
#define sprites_parkCGBPal6c1 8935
#define sprites_parkCGBPal6c2 6596
#define sprites_parkCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sprites_parkCGBPal7c0 6076
#define sprites_parkCGBPal7c1 8935
#define sprites_parkCGBPal7c2 6596
#define sprites_parkCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char sprites_park[];

/* End of SPRITESPARK.H */
